Vagrant.configure("2") do |config|

    config.vm.box = "bento/ubuntu-22.04"

    config.vm.hostname = "docker-up-and-running"
    config.vm.network "private_network", ip: "192.168.56.33"

    config.vm.provision "shell", path: "vagrant_scripts/install_monitoring.sh"
    config.vm.provision "shell", path: "vagrant_scripts/install_docker.sh"

    config.vm.provider "virtualbox" do |v|
        v.memory = 8192
        v.cpus = 8
    end
    
end
